// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZyt-Mezgj_iCoR03rRmZfqV8SSpBNjo',
    appId: '1:249150452209:web:fbefa59267c542427ad450',
    messagingSenderId: '249150452209',
    projectId: 'skill-light',
    authDomain: 'skill-light.firebaseapp.com',
    storageBucket: 'skill-light.firebasestorage.app',
    measurementId: 'G-0MXHBH2GGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARuPtsJst7wAyZPa1uLcT9Wk3g8ZTCd0',
    appId: '1:249150452209:android:6c5d8213a2c92ead7ad450',
    messagingSenderId: '249150452209',
    projectId: 'skill-light',
    storageBucket: 'skill-light.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4bg1I7D8NLLEaSmmmk0a6sxKU9buYPE',
    appId: '1:249150452209:ios:f36be6bfa50191f77ad450',
    messagingSenderId: '249150452209',
    projectId: 'skill-light',
    storageBucket: 'skill-light.firebasestorage.app',
    iosBundleId: 'com.example.skillLightFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW4bg1I7D8NLLEaSmmmk0a6sxKU9buYPE',
    appId: '1:249150452209:ios:f36be6bfa50191f77ad450',
    messagingSenderId: '249150452209',
    projectId: 'skill-light',
    storageBucket: 'skill-light.firebasestorage.app',
    iosBundleId: 'com.example.skillLightFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGZyt-Mezgj_iCoR03rRmZfqV8SSpBNjo',
    appId: '1:249150452209:web:742a575e7e9ebdeb7ad450',
    messagingSenderId: '249150452209',
    projectId: 'skill-light',
    authDomain: 'skill-light.firebaseapp.com',
    storageBucket: 'skill-light.firebasestorage.app',
    measurementId: 'G-JE451J9G1C',
  );
}
